#!/bin/bash
# This script is meant to help overcome mind blocks the way that a rubber
# ducky. (Look at it as a digital rubber ducky). Concept and content borrowed
# from duckie.me 

echo "       ,--------. "
echo "     ,           ."
echo "    ;    __   ___|"
echo "    ;  ( (*) ( (*) "
echo "    |      ___   |"
echo "   ,   ,-      __ .           ."
echo "  (   ( .________ .)--._        _"
echo "   *.    .    (      .   ------/ .\\"
echo "    ,')    . ._))  ,'  .    .  , ,  ;"
echo "  .    .     --   /     ).    .      ;"
echo " ;       -       /        )         ;"
echo " \                        )        ;"
echo "  \                      ;       ;"
echo "   \                 ~~~        ;"
echo "    .                         _; "
echo "      .                   ,--;"
echo "        -._________,-----;"



line1="Can you describe the problem in a paragraph? Please use small sentences, I'm only a duck."
line2="What should I call the function / object / thing that is misbehaving?"

echo $line1
read problem
echo $line2
read name
line3="Can you explain what "${name}" does?"
echo $line3
read purpose
line4="Do you fully understand how it does what it does? Could you split "${name}" into smaller chunks?"
echo $line4
read yesNo
line5="What parts of "${name}" are you certain work, and where are your 'unknowns'?"
echo $line5
read parts
line6="Is "${name}" being compiled? Can you restart the compiler?"
echo $line6
read couldRestart
line7="Is something similar to "${name}" being used elsewhere? Could common elements be shared?"
echo $line7
read similarity
line8="How is "${name}" modified?"
echo $line8
read modification
line9="Could "${name}", or variables within it, be somehow overwritten or overridden?"
echo $line9
read overwritten
line10="Is everything in "${name}" your code? Could you replace uncertainties with debugging statements?"
echo $line10
read uncertainties
line11="Why do you need "${name}"?"
echo $line11
read need
line12="Sorry, my super-duck-powers have failed. Have you tried google or stack overflow?"
echo $line12
